name: Raphi See
favicon: null
layout_spectrum: 1
typography_spectrum: 0.71456
title: photography and other interests
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5e7f6'
    - '#191714'
    - '#2c4510'
    - '#7fa527'
    - '#6c716d'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
